### PR TITLE
declare ssize_t in FreeBSD

### PR DESCRIPTION
**Pull request by lalawue**
decleare ssize_t in FreeBSD

### CODE REVIEW

**Comment by sonoro1234** [comment]
isnt that enought?

https://github.com/LuaJIT/LuaJIT/commit/52ea1a30afc204553c99126ab43c2b16f2bd0182

May be you are using LuaJIT 2.0 instead of 2.1, then either raise an issue in LuaJIT repo for that or wrap the typedef to be done only if version is 2.0 (jit.version_number < 20100)

**Comment by lalawue** [comment]
> isnt that enought?
> 
> [LuaJIT/LuaJIT@52ea1a3](https://github.com/LuaJIT/LuaJIT/commit/52ea1a30afc204553c99126ab43c2b16f2bd0182)
> 
> May be you are using LuaJIT 2.0 instead of 2.1, then either raise an issue in LuaJIT repo for that or wrap the typedef to be done only if version is 2.0 (jit.versio

Ok, I wrap the typeof when jit.version_num < 20100.

**Comment by sonoro1234** [comment]
Thanks!!

**Comment by sonoro1234** [comment]
Just did a commit to undo that and do `typedef intptr_t ssize_t` when ssize_t was not defined (LuaJIT 2.0). Now ssize_t is different in 32 and 64 bits.

**Pull request merged**
