### PR TITLE
Support BSD stat

### PR DESCRIPTION
**Pull request by lalawue**
Support BSD stat

### CODE REVIEW

**Comment by sonoro1234** [comment]
The first commit in this PR wouldnt be neccesary. It was already in sonoro1234/unicode.

You should base your commits on the last commit of sonoro1234/unicode which for me is master:
Always pull from sonoro1234/unicode to keep this branch as master then make a new branch for modification, make your changes, and then make a PR from this branch. When it is merged in sonoro1234/unicode you can pull from it again to always be in sync.

Your lalawue/unicode branch should always be identical to sonoro1234/unicode to avoid this conflicts.

**Comment by sonoro1234** [comment]
Thanks!!

**Comment by lalawue** [comment]
you are welcome~

**Comment by lalawue** [comment]
Sorry about that,  sometimes I login only in weekend.

**Pull request merged**
