### PR TITLE
check OSX _DARWIN_FEATURE_64_BIT_INODE with readdir

### PR DESCRIPTION
**Pull request by xixihahahei**
check OSX _DARWIN_FEATURE_64_BIT_INODE with system version, only test under Apple Silicon M1

### CODE REVIEW

**Comment by sonoro1234** [comment]
If @stuta tries it succesfully then it will be merged

**Comment by sonoro1234** [comment]
@xixihahahei Cant it be solved with `ffi.abi` or `ffi.arch` instead of `prog_read`?

**Comment by xixihahahei** [comment]
> @xixihahahei Cant it be solved with `ffi.abi` or `ffi.arch` instead of `prog_read`?

it depends on system version in man page. (I take it below)

I check https://en.wikipedia.org/wiki/Mac_OS_X_Tiger, in system version 10.4 it support 64bit, and system lifetime has a transition from PowerPC to Intel.

And 10.5 announced in 2007, https://en.wikipedia.org/wiki/Mac_OS_X_Leopard.

it seams easier to check system version than `ffi.abi` and `ffi.arch`.

If ffi_lfs.lua only support OSX system version >= 10.5, no prog_read needed, it's an option.

man 2 stat
```
_DARWIN_FEATURE_64_BIT_INODE
     In order to accommodate advanced capabilities of newer file systems, the struct stat, struct statfs, and
     struct dirent data structures were updated in Mac OSX 10.5.

     The most obvious change is the increased size of ino_t from 32 bits to 64 bits.  As a consequence, storing
     an ino_t in an int is no longer safe, and file formats storing ino_t as 32-bit values may need to be
     updated.  There are other changes as well, such as the widening of f_fstypename, f_mntonname, and
     f_mntfromname in struct statfs.  Please refer to dir(5) for more detail on the specific changes to the
     other affected data structures.

     On platforms that existed before these updates were available, ABI compatibility is achieved by providing
     two implementations for related functions: one using the legacy data structures and one using the updated
     data structures.  Variants which make use of the newer structures have their symbols suffixed with
     $INODE64.  These $INODE64 suffixes are automatically appended by the compiler tool-chain and should not be
     used directly.

     Platforms that were released after these updates only have the newer variants available to them.  These
     platforms have the macro _DARWIN_FEATURE_ONLY_64_BIT_INODE defined.

     The _DARWIN_FEATURE_64_BIT_INODE macro should not be set directly.  Instead, developers should make use of
     the _DARWIN_NO_64_BIT_INODE or _DARWIN_USE_64_BIT_INODE macros when the default variant is not desired.
     The following table details the effects of defining these macros for different deployment targets.

                                   _DARWIN_FEATURE_ONLY_64_BIT_INODE not defined
                              -------------------------+-------------------------------
                                                       |       Deployment Target
                                   user defines:       |   < 10.5       10.5    > 10.5
                              -------------------------+-------------------------------
                                       (none)          |   32-bit      32-bit   64-bit
                              _DARWIN_NO_64_BIT_INODE  |   32-bit      32-bit   32-bit
                              _DARWIN_USE_64_BIT_INODE |   32-bit      64-bit   64-bit
                              -------------------------+-------------------------------

                                     _DARWIN_FEATURE_ONLY_64_BIT_INODE defined
                              -------------------------+-------------------------------
                                   user defines:       | Any Deployment Target
                              -------------------------+-------------------------------
                                       (none)          | 64-bit-only
                              _DARWIN_NO_64_BIT_INODE  |   (error)
                              _DARWIN_USE_64_BIT_INODE | 64-bit-only
                              -------------------------+-------------------------------

           32-bit       32-bit inode values are enabled, and the legacy structures involving the ino_t type are
                        in use.  The macro _DARWIN_FEATURE_64_BIT_INODE is not defined.

           64-bit       64-bit inode values are enabled, and the expanded structures involving the ino_t type
                        are in use.  The macro _DARWIN_FEATURE_64_BIT_INODE is defined, and loader symbols will
                        contain the $INODE64 suffix.

           64-bit-only  Like 64-bit, except loader symbols do not have the $INODE64 suffix.

           (error)      A compile time error is generated.
```

**Comment by stuta** [comment]
This works with a small tweak. Thanks!

* prog_read could return r:gsub("\n", "") - but it works without it - no need to make this slower
* tomumber("12.0.1") fails, remove tonumber and compare with string "10.5"

**Comment by sonoro1234** [comment]
> 
> 
> This works with a small tweak. Thanks!
> 
>     * prog_read could return r:gsub("\n", "")
> 
>     * tomumber("12.0.1") fails, remove tonumber and compare with string "10.5"

Althought `print("10.10" >= "10.5")` prints false!!
So that version compare should be done by splitting version string by `.` and lexicographical compare substrings

@xixihahahei Could you implement those changes?

**Comment by stuta** [comment]
Hmm, this works in arm64, but now in rosetta x64 filename is missing the first character. For example, instead of returning keyword.json, it is returning eyword.json.

**Comment by sonoro1234** [comment]
> Hmm, this works in arm64, but now in rosetta x64 filename is missing the first character. For example, instead of returning keyword.json, it is returning eyword.json.

@stuta Does it work with roseta x64 with original code?

**Comment by sonoro1234** [comment]
It should be solved for all osx versions:
How many different dirent structures are possible on osx?
How to discriminate which one is the correct one?

looking at https://opensource.apple.com/  I was unable to find `sys/dirent.h` for example

**Comment by stuta** [comment]
Yes, the original code works with rosetta. This is simple, function prog_read() is not needed. All we need is to fix osx arm64 is to use new structure with:
```lua
if OS == 'OSX' and ffi.arch == "arm64" then 
```

**Comment by sonoro1234** [comment]
> 
> 
> Yes, the original code works with rosetta. This is simple, function prog_read() is not needed. All we need is to fix osx arm64 is to use new structure with:
> 
> ```lua
> if OS == 'OSX' and ffi.arch == "arm64" then 
> ```

@stuta Which system version has your rosetta x64?

**Comment by sonoro1234** [comment]
according to https://stackoverflow.com/a/54265243 it seems that looking for `st_birthtime` in `stat -s .` output would help to discriminate
I am not able to try it as I dont have osx, but it would help us to solve not only which `struct dirent` is valid but also which `struct stat`

It could be something as:

```lua
local function isINO64()
    local f = io.popen('stat -s .', 'r')
    if f then
        local r = f:read("*a")
        f:close()
        if r:match"st_birthtime" then
            return true
        else
            return false
        end
    end
end
```

**Comment by stuta** [comment]
I have 12.0.1. But old code works with all other macs and rosetta x64 emulation in M1 Macs. Only osx arm64 needs this new struct.

**Comment by sonoro1234** [comment]
> 
> 
> I have 12.0.1. But old code works with all other macs and rosetta x64 emulation in M1 Macs. Only osx arm64 needs this new struct.

Googling around it seems to depend on system version but also on some defines which vary in very esoteric ways. I feel that my above `stat -s` proposal could solve it all.

**Comment by sonoro1234** [comment]
https://github.com/sonoro1234/luafilesystem/tree/ino64 implements this.

@stuta could you try it with both osxs?

**Comment by stuta** [comment]
There's a typo in code, it should be `if r:match"st_birthtime" then`.

But now native arm64 and rosetta are missing the first char, so both of them do not work.

**Comment by xixihahahei** [comment]
> https://github.com/sonoro1234/luafilesystem/tree/ino64 implements this.
> 
> @stuta could you try it with both osxs?

I think the problem is the program LuaJIT with macro _DARWIN_FEATURE_64_BIT_INODE defined, so I use another way to solve it, then make a force push.

**Comment by xixihahahei** [comment]
> There's a typo in code, it should be `if r:match"st_birthtime" then`.
> 
> But now native arm64 and rosetta are missing the first char, so both of them do not work.

Can You try this branch again? I make a force push, using another way to solve this.

**Comment by sonoro1234** [comment]
@stuta I have updated ino64 branch to post result. I would love to see the result in both osxs besides trying last xixihahahei solution.

**Comment by stuta** [comment]
Same problem even in old Intel x64 Mojave -machine. The first character is missing. Maybe you should test this in normal old Intel Mac first, I can test M1 after x86/x64 works.

**Comment by xixihahahei** [comment]
> Same problem even in old Intel x64 Mojave -machine. The first character is missing. Maybe you should test this in normal old Intel Mac first, I can test M1 after x86/x64 works.

I test my latest force push in Intel x64 in 10.12, works ok, and M1 ok too.

**Comment by sonoro1234** [comment]
@stuta Still missing post from ino64 branch
Perhaps @xixihahahei changes would need some post also to clarify what is happening
Also, it would be usefull to have ffi.arch from every osx and if it is 64bits or not

**Comment by stuta** [comment]
I did try yesterday with ino64. The first char is missing in x64. Today I tried in M1, it works with arm64, but like yesterday in Intel x64 it has the first char missing.

**Comment by xixihahahei** [comment]
> @stuta Still missing post from ino64 branch
> Perhaps @xixihahahei changes would need some post also to clarify what is happening
> Also, it would be usefull to have ffi.arch from every osx and if it is 64bits or not

in OSX with 64bit system, first using _DARWIN_FEATURE_64_BIT_INODE NOT defined struct dirent (32bit), then I run opendir('/tmp') and read dirent value from C.

Here I assume the first entry is '.' as inode creation order, it means it is /tmp dir itself, then I check it d_type is 4 (directory), d_namlen == 1 and d_name == '.'.

For 32bit struct dirent and 64bit struct dirent, d_type, d_namlen, d_name entry location are so different and can not have the correct value in anytime.

if 32bit dirent failed, I turn to check 64bit dirent with another name struct dirent64, just ffi.cast to it, here I assume readdir will return enough space for 64bit dirent.

run above test again, If it success, I will treat every readdir return value is 64bit and set readdir_cast to 'dirent64_t *' for next readdir() call.

**Comment by xixihahahei** [comment]
> I did try yesterday with ino64. The first char is missing in x64. Today I tried in M1, it works with arm64, but like yesterday in Intel x64 it has the first char missing.

May be you should use my latest force push branch, and I have test it under Intel x64 10.12 and M1, works fine.

**Comment by sonoro1234** [comment]
> if 32bit dirent failed, I turn to check 64bit dirent with another name struct dirent64, just ffi.cast to it, here I assume readdir will return enough space for 64bit dirent.

@xixihahahei May be it is better to to asume it fits in a dirent_64 struct and if test fail cast it to a dirent_32 struct which is smaller.

@stuta Probably `arm64` implies INODE_64 but it does not mean that all the others are NOT_INODE_64. So we should solve it in a more general way: To find out what should be done, it would be very useful to have results from several tests in every different osx:
Version number, is64bit, ffi.arch, `stat -s .` post and if it fits in dirent_64 struct (xixihahahei test)
Perhaps you could write those tests or I could add `testINO64.lua` to ino64 branch.

**Comment by xixihahahei** [comment]
> > if 32bit dirent failed, I turn to check 64bit dirent with another name struct dirent64, just ffi.cast to it, here I assume readdir will return enough space for 64bit dirent.
> 
> @xixihahahei May be it is better to to asume it fits in a dirent_64 struct and if test fail cast it to a dirent_32 struct which is smaller.
> 
> @stuta Probably `arm64` implies INODE_64 but it does not mean that all the others are NOT_INODE_64. So we should solve it in a more general way: To find out what should be done, it would be very useful to have results from several tests in every different osx: Version number, is64bit, ffi.arch, `stat -s .` post and if it fits in dirent_64 struct (xixihahahei test) Perhaps you could write those tests or I could add `testINO64.lua` to ino64 branch.

I think using dirent_32 first is safer than dirent_64,

**Comment by sonoro1234** [comment]
@stuta and @xixihahahei Just pushed `testINO64.lua` to ino64 branch
Could you please run it in you several osx?

**Pull request closed without merging**
